Install-WindowsFeature -Name File-Services,FS-FileServer,FS-DFS-Namespace,FS-DFS-Replication,Web-Server,
Web-WebServer,Web-Common-Http,Web-Default-Doc,Web-Dir-Browsing,Web-Http-Errors,Web-Static-Content,
Web-Http-Redirect,Web-DAV-Publishing,Web-Health,Web-Http-Logging,Web-Custom-Logging,Web-Log-Libraries,
Web-Request-Monitor,Web-Http-Tracing,Web-Performance,Web-Stat-Compression,Web-Dyn-Compression,Web-Security,
Web-Filtering,Web-Basic-Auth,Web-IP-Security,Web-Url-Auth,Web-Windows-Auth,Web-App-Dev,Web-Net-Ext,Web-Net-Ext45,
Web-Asp-Net45,Web-ISAPI-Ext,Web-ISAPI-Filter,Web-Ftp-Server,Web-Ftp-Service,Web-Ftp-Ext,Web-Mgmt-Tools,Web-Mgmt-Console,
Web-Scripting-Tools,Web-Mgmt-Service,NET-Framework-Features,NET-Framework-Core,NET-HTTP-Activation,NET-Non-HTTP-Activ,
NET-Framework-45-Features,NET-Framework-45-Core,NET-Framework-45-ASPNET,NET-WCF-Services45,NET-WCF-HTTP-Activation45,
NET-WCF-Pipe-Activation45,NET-WCF-TCP-Activation45,NET-WCF-TCP-PortSharing45,
RSAT-DFS-Mgmt-Con,Telnet-Client,WAS,WAS-Process-Model,WAS-NET-Environment,WAS-Config-APIs